<a href="https://colab.research.google.com/github/DaniloMendez30/conversorMoneda2/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
lista = [1,2,3,4,5,6,7,8,9]
ar = np.array(lista)
print(ar)

[1 2 3 4 5 6 7 8 9]


In [6]:
matriz = [[1,2,3], [3,4,5],[6,7,8]]
matriz = np.array(matriz)
print(matriz)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [28]:
matriz_3d = [ [[1, 2],
     [3, 4]],
     [[5, 6],
     [7, 8]]
            ]
matriz_3d = np.array(matriz_3d)
print(matriz_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Indexado:
> 
El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se empiezan a contar desde 0.




In [7]:
matriz[0,2] #accedemos al indice de la matriz fila posición 0 y columna posición 2

3

In [14]:
matriz[1:, 0:2] #empezamos desde la posicion 1 para adelante y traemos desde la columna posicion 0 hasta 2

array([[3, 4],
       [6, 7]])

In [29]:
matriz_3d[:,0,0] # Todas las matrices, primera fila, primera columna

array([1, 5])

## Slicing

> Nos permite extraer varios datos, tiene un comienzo y un final.



In [13]:
ar[1:3] #nos permite recorrer la lista desde la posicion 0 a la 3

array([2, 3])

In [11]:
ar[::3] #avanza cada tres pociciones 

array([1, 4, 7])