<a href="https://colab.research.google.com/github/DaniloMendez30/conversorMoneda2/blob/main/dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
vector = np.array([1,2,3,4])
vector.ndim # ndim me dice la dimesion que tiene los datos

1

In [7]:
matriz = np.array([[1,2,3],[5,6,7]])
matriz.ndim

2

## Agregar dimensiones

In [14]:
vector = np.array([1,2,3], ndmin =10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

## Eliminar dimensiones

In [15]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) #eliminar dimnesiones que no se estan usando
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
